### ISSUE TITLE
Failed to run sudo ./build/benchmark, meets ERROR:  Assertion `nb_ports == 1' failed

### ISSUE THREAD

**Issue by shoveller86** [pzrq/megakv#1]

**Comment by shoveller86** [comment]
Hello, I have build `megakv` and `benchmark`   exacutable app successfully.  And `./megakv`  run OK,  but when I run `sudo ./build/benchmark`   meet errors:

```
EAL: Detected 16 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
benchmark: /home/wei/GPPIM/MegaKV/megakv/benchmark/benchmark.c:733: main: Assertion `nb_ports == 1' failed.
Aborted

```
Is there any configuration to solve this problem?  thank you.

**Comment by pzrq** [comment]
@alphaRGB I honestly don't know - https://github.com/pzrq/megakv/blob/master/src/include/mega_config.h looks like it might be "config"?

What environment are you running this on? Your local machine, [AWS](https://aws.amazon.com/) or something else?

Sorry I can't find the fork this came from at the moment, or the whitepaper, which probably had more details.

If it's helpful to you happy to accept PRs, though you may be better off forking it with any updates or fixes that work for you and your environment.

**Comment by shoveller86** [comment]
> @alphaRGB I honestly don't know - https://github.com/pzrq/megakv/blob/master/src/include/mega_config.h looks like it might be "config"?
> 
> What environment are you running this on? Your local machine, [AWS](https://aws.amazon.com/) or something else?
> 
> Sorry I can't find the fork this came from at the moment, or the whitepaper, which probably had more details.
> 
> If it's helpful to you happy to accept PRs, though you may be better off forking it with any updates or fixes that work for you and your environment.

I have run `benchmark`  on local machine, with ubuntu 18.04,  with 2 intel CPUs + 2 NVIDIA V100 GPUs + 265G Memory.     And I have an another question：

I want to get the 3 results of the experiments in paper- megaKV:  https://dl.acm.org/doi/pdf/10.14778/2809974.2809984  :  
Figure 13:  Theoretical Maxium Speed for One GPU   ~  Figure 15 Mega-KV Performance with Large Key-Value size.
But I down't find where to set  the （Scheduling Cycles C (us)  in  code  ?   is this variable ? https://github.com/pzrq/megakv/blob/c41f25965f8674b6707c1c3490fe970b371c4742/src/macros.h#L41 ,   can I set it to 120, 140, 160 directly like the Figure 14 in paper  when I run this executable app: https://github.com/pzrq/megakv/blob/c41f25965f8674b6707c1c3490fe970b371c4742/src/mega.c#L523
